version: "3.7"

services:
  app:
    build:
      args:
        user: coodesh-app
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: coodesh-app
    container_name: coodesh-app
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "4200:4200"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    networks:
      - coodeshNetwork
networks:
  coodeshNetwork:
    driver: bridge
